### ISSUE TITLE
Fail: Gcone_which_mex 232: cannot find jf_mex or cbct_mex

### ISSUE THREAD

**Issue by lilimkk** [JeffFessler/mirt#25]
After I run setup.m and ir_mex_build.m，I still have some question to run cone-beam-ct_example.m。The fail message is as following:
Fail: Gcone_which_mex 232: cannot find jf_mex or cbct_mex
So where I can get jf_mex or cbct_mex?
Thanks.

**Comment by JeffFessler** [comment]
As explained in the README, not all mex files are available in the github version.
So you need to get the .tgz file from my web site - see url in README.
Sorry about that but maintaining mex files with github is not so easy...
