### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by bruceandbruce** [JeffFessler/mirt#29]
I have just started researching magnetic resonance fingerprinting, which involves creating a spiral trajectory to sample k-space. I don't understand how to do this. I have read relevant papers that mention nufft, but I don't seem to be able to find the inverse process of nufft, which means I don't know how to restore the sampled k-space to the image domain.

**Comment by JeffFessler** [comment]
In general the NUFFT operator is not invertible.  In fact it is not even square usually.
You can have a fast approximate inverse using density compensated gridding.
For the theory see:
https://web.eecs.umich.edu/~fessler/book/c-four.pdf
Or you can use iterative methods.
